---
# - name: Install Splunk OpenTelemetry Collector
- hosts: gateway
  become: yes
  # For Windows "become: yes" will raise error.
  # "The Powershell family is incompatible with the sudo become plugin". Remove "become: yes" tag to run on Windows
  roles:
    - ../roles/collector
  vars:
    splunk_access_token: "{{ vault_splunk_access_token }}"
    splunk_realm: eu0
  vars_files:
    - "../environments/vault.yml"

- hosts: agents
  become: yes
  # For Windows "become: yes" will raise error.
  # "The Powershell family is incompatible with the sudo become plugin". Remove "become: yes" tag to run on Windows
  roles:
    - ../roles/collector
  vars:
    splunk_access_token: "{{ vault_splunk_access_token }}"
    splunk_realm: eu0
  vars_files:
    - "../environments/vault.yml"

- hosts: windows
  #become: yes
  # For Windows "become: yes" will raise error.
  # "The Powershell family is incompatible with the sudo become plugin". Remove "become: yes" tag to run on Windows
  roles:
    - ../roles/collector
  vars:
    splunk_access_token: "{{ vault_splunk_access_token }}"
    splunk_realm: eu0
  vars_files:
    - "../environments/vault.yml"